[package]
name = "bandersnatch-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec-vrfs = { path = "../ark-ec-vrfs" , default-features = false, features = ["bandersnatch", "ring"] }
ark-ed-on-bls12-381-bandersnatch = { version = "0.4.0", default-features = false }

web-sys = { version = "0.3", features = ["console"] }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
